services:
  db:
    image: sivadockerz/pyapp:dbimage
    deploy:
      replicas: 3
    ports:
      - 3306:3306
    networks:
      - mynetwork
  auth_service:
    image: sivadockerz/pyapp:authimage
    deploy:
      replicas: 3
    ports:
      - "5001:5001"
    networks:
      - mynetwork
    depends_on:
      - db
    
  
  book_service:
    image: sivadockerz/pyapp:bookimage
    deploy:
      replicas: 3
    ports:
      - "5002:5002"
    networks:
      - mynetwork
    depends_on:
      - db

  borrow_service:
    image: sivadockerz/pyapp:borrowimage
    deploy:
      replicas: 3
    ports:
      - "5003:5003"
    networks:
      - mynetwork
    depends_on:
      - db

  frontend:
    image: sivadockerz/pyapp:frontend
    deploy:
      replicas: 3
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - auth
      - book
      - borrow

networks:
  mynetwork:
    driver: overlay
