services:
  db:
    image: sivadockerz/pyrepo:dbimage
    deploy:
      replicas: 1
    ports:
      - "3306:3306
    networks:
      - mynetwork
  auth:
    image: sivadockerz/pyrepo:authimage
    deploy:
      replicas: 1
    ports:
      - "5001:5001"
    networks:
      - mynetwork
    depends_on
      - db
    
  
  book:
    image: sivadockerz/pyrepo:bookimage
    deploy:
      replicas: 1
    ports:
      - "5002:5002"
    networks:
      - mynetwork
    depends_on
      - db

  borrow:
    image: sivadockerz/pyrepo:borrowimage
    deploy:
      replicas: 1
    ports:
      - "5003:5003"
    networks:
      - mynetwork
    depends_on
      - db

  frontend:
    image: sivadockerz/pyrepo:frontend
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on
      - auth
      - book
      - borrow

networks:
  mynetwork:
    driver: overlay
